spring.application.name=api

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.jackson.default-property-inclusion=non_null

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=INTEG
spring.datasource.password=INTEG
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=0d19e2bbf83a64
spring.mail.password=0dc7d71a0bbe28
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=34101   
server.servlet.context-path=/

# SFTP Server Configuration
sftp.host=localhost
sftp.port=2222
sftp.username=fiiconnect
sftp.password=fiiconnect

sftp.inbound.remote.dir=/faculty_files
sftp.inbound.local.dir=../../SFTP_remote_files
