spring.application.name=api

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=fiiConnect
spring.datasource.password=parola
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=0d19e2bbf83a64
spring.mail.password=0dc7d71a0bbe28
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


server.port=34101   