drop sequence USERS_SEQ;
drop sequence ROLES_SEQ;
drop sequence PASSWORD_RESET_TOKEN_SEQ;
drop sequence NOTIFICATIONS_SEQ;
drop sequence USER_PROFILE_SEQUENCE;

commit;

CREATE SEQUENCE USERS_SEQ                     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ROLES_SEQ                     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE PASSWORD_RESET_TOKEN_SEQ      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE NOTIFICATIONS_SEQ             START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE USER_PROFILE_SEQUENCE         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

commit;
